spring:
  application:
    name: java-coding-exercise
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dll-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  show-actuator: true